version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - cardmarket:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true
#-------------------------------------------------------------------------#
  backend:
    build: ./
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    links:
      - db
    depends_on:
      - db
    tty: true
#-------------------------------------------------------------------------#
volumes:
  cardmarket: