version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - cardmarket:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true
    command: sh -c "mysqladmin -u root -p'root' password '$MYSQL_ROOT_PASSWORD'"
#-------------------------------------------------------------------------#
  backend:
    build: ./
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    links:
      - db
    depends_on:
      - db
    tty: true
#-------------------------------------------------------------------------#
volumes:
  cardmarket: