version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    volumes:
      - cardmarket:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    tty: true
#-------------------------------------------------------------------------#
  backend:
    build: ./
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=${{ secrets.MYSQL_HOST }}
      - DB_PORT=${{ secrets.MYSQL_PORT }}
      - DB_USER=${{ secrets.MYSQL_USER }}
      - DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - DB_NAME=${{ secrets.MYSQL_DATABASE }}
    links:
      - db
    depends_on:
      - db
    tty: true
#-------------------------------------------------------------------------#
volumes:
  cardmarket: