version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cardmarket
      - MYSQL_PASSWORD=root
    volumes:
      - cardmarket:/var/lib/mysql
    restart: always
    tty: true
#-------------------------------------------------------------------------#
  backend:
    build: ./
    container_name: backend
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=cardmarket
    links:
      - db
    depends_on:
      - db
    tty: true
#-------------------------------------------------------------------------#
volumes:
  cardmarket: