name: Docker Image CI

on:
  push:
    branches:
      - main
      - backend
  pull_request:
    branches: [main]
    types:
      - closed
#-------------------------------------------------------#
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test the code
        run: echo "Here will be the integration tests"

#-------------------------------------------------------#
  build:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd backend
          sudo docker-compose up -d --build --force-recreate