name: Docker Image CI

on:
  push:
    branches:
      - main
      - backend
  pull_request:
    branches: [main]
    types:
      - closed
#-------------------------------------------------------#
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test the code
        run: echo "Here will be the integration tests"

#-------------------------------------------------------#
  build:
    needs: test
    runs-on: self-hosted
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          cd backend
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env
          echo "DB_HOST=${MYSQL_HOST}" >> .env
          echo "DB_PORT=${MYSQL_PORT}" >> .env
          echo "DB_USER=${MYSQL_USER}" >> .env

      - name: Build the Docker image
        run: |
          cd backend
          sudo docker-compose up -d --build --force-recreate