name: Docker Image CI

on:
  push:
    branches:
      - main
      - backend
  pull_request:
    branches: [main]
    types:
      - closed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd backend
          sudo docker-compose up -d --build --force-recreate